name: Release

on:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@917f7d59f22e82a5ddcaef409923426fd7aa6327
      with:
        allowed-endpoints: 
          agent.api.stepsecurity.io:443
          api.github.com:443
          github.com:443
          goreleaser.com:443
          objects.githubusercontent.com:443
          proxy.golang.org:443
          storage.googleapis.com:443
          uploads.github.com:443
    - name: Checkout
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
    - name: Set up Go 
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: 1.17    
    - uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}