name: Release

on:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@7206db2ec98c5538323a6d70e51f965d55c11c87
      with:
       allowed-endpoints: 
        api.github.com:443
        beta.api.stepsecurity.io:443
        github.com:443
        int.api.stepsecurity.io:443
        pipelines.actions.githubusercontent.com:443
        proxy.golang.org:443
        step-security-agent.s3.us-west-2.amazonaws.com:443
        storage.googleapis.com:443
        sts.us-west-2.amazonaws.com:443
    - name: Checkout
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
    - name: Set up Go 
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: 1.17
    - run: go build -ldflags="-s -w" -o ./agent
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - run: aws s3 cp ./agent s3://step-security-agent/refs/heads/int/agent --acl public-read
    - name: Integration test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
    - uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}