name: Release

on:
  push:
    branches:
      - main
      
jobs:
  release:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@main
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go 
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.17
    - run: go build -ldflags="-s -w" -o ./agent
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - run: aws s3 cp ./agent s3://step-security-agent/refs/heads/int/agent --acl public-read
    - name: Integration test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
    - run: aws s3 cp ./agent s3://step-security-agent/refs/heads/beta/agent --acl public-read
