name: Test
on:
  push:

permissions: read-all    

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@7206db2ec98c5538323a6d70e51f965d55c11c87
      with:
        allowed-endpoints: 
          beta.api.stepsecurity.io:443
          codecov.io:443
          github.com:443
          proxy.golang.org:443
          storage.googleapis.com:443
    - name: Checkout
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
    - name: Set up Go 
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: 1.17
    - name: Run coverage
      run: sudo go test -coverprofile=coverage.txt -covermode=atomic
    - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b