name: Test
on:
  push:
    
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@main
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go 
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.17
    - name: Run coverage
      run: sudo go test -coverprofile=coverage.txt -covermode=atomic
    - uses: codecov/codecov-action@v2